import { BrainCircuit, RotateCcw, Sparkles } from "lucide-react";
import { useState } from "react";

import { FactorBarChart } from "@/charts/Charts";
import { AIInsight, SectionCard } from "@/components/shared/Layout";
import { RiskGauge } from "@/components/shared/RiskGauge";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { riskStyles } from "@/lib/risk";
import { cn } from "@/lib/utils";
import { runPrediction, type PredictionInput, type PredictionResult } from "@/services/api";

const DEFAULTS: PredictionInput = {
  attendance: 72,
  cgpa: 6.8,
  failedSubjects: 1,
  assignmentCompletion: 74,
  previousGpa: 7.4,
  lmsActivity: 62,
  participation: 58,
  financialStress: 45,
  previousSemesterPerformance: 70,
};

const FIELDS: { key: keyof PredictionInput; label: string; min: number; max: number; step: number; suffix?: string }[] = [
  { key: "attendance", label: "Attendance", min: 0, max: 100, step: 1, suffix: "%" },
  { key: "cgpa", label: "Current CGPA", min: 0, max: 10, step: 0.1 },
  { key: "previousGpa", label: "Previous semester GPA", min: 0, max: 10, step: 0.1 },
  { key: "failedSubjects", label: "Failed subjects", min: 0, max: 6, step: 1 },
  { key: "assignmentCompletion", label: "Assignment completion", min: 0, max: 100, step: 1, suffix: "%" },
  { key: "lmsActivity", label: "LMS activity", min: 0, max: 100, step: 1, suffix: "%" },
  { key: "participation", label: "Class participation", min: 0, max: 100, step: 1, suffix: "%" },
  { key: "financialStress", label: "Financial stress index", min: 0, max: 100, step: 1 },
  { key: "previousSemesterPerformance", label: "Previous semester performance", min: 0, max: 100, step: 1, suffix: "%" },
];

export function PredictionSimulator() {
  const [input, setInput] = useState<PredictionInput>(DEFAULTS);
  const [result, setResult] = useState<PredictionResult | null>(null);
  const [running, setRunning] = useState(false);

  const set = (key: keyof PredictionInput, value: number) => setInput((p) => ({ ...p, [key]: value }));

  const run = () => {
    setRunning(true);
    setTimeout(() => {
      setResult(runPrediction(input));
      setRunning(false);
    }, 650);
  };

  return (
    <div className="grid gap-5 xl:grid-cols-[1fr_1fr]">
      <SectionCard
        title="Prediction Simulator"
        description="Adjust the model inputs to see how dropout probability responds"
        actions={
          <Button
            variant="ghost"
            size="sm"
            onClick={() => {
              setInput(DEFAULTS);
              setResult(null);
            }}
          >
            <RotateCcw className="size-4" /> Reset
          </Button>
        }
      >
        <div className="grid gap-5 sm:grid-cols-2">
          {FIELDS.map((f) => (
            <div key={f.key} className="space-y-2">
              <div className="flex items-center justify-between gap-2">
                <Label className="min-w-0 truncate text-xs text-muted-foreground">{f.label}</Label>
                <span className="shrink-0 rounded-md bg-muted px-2 py-0.5 font-display text-xs font-bold tabular-nums">
                  {input[f.key]}
                  {f.suffix ?? ""}
                </span>
              </div>
              <Slider
                value={[input[f.key]]}
                min={f.min}
                max={f.max}
                step={f.step}
                onValueChange={(v) => set(f.key, v[0] ?? 0)}
              />
            </div>
          ))}
        </div>
        <Button className="mt-6 w-full" size="lg" onClick={run} disabled={running}>
          {running ? (
            <>
              <BrainCircuit className="size-4 animate-pulse" /> Running model…
            </>
          ) : (
            <>
              <Sparkles className="size-4" /> Run AI prediction
            </>
          )}
        </Button>
      </SectionCard>

      <SectionCard title="Prediction Result" description="Generated by dropout prediction model v3.2.1">
        {!result ? (
          <div className="grid min-h-[420px] place-items-center rounded-xl border border-dashed border-border text-center">
            <div className="max-w-xs p-6">
              <span className="mx-auto grid size-12 place-items-center rounded-2xl bg-primary/10 text-primary">
                <BrainCircuit className="size-6" />
              </span>
              <p className="mt-4 font-display text-sm font-semibold">No prediction yet</p>
              <p className="mt-1.5 text-xs text-muted-foreground">
                Set the student parameters on the left and run the model to see dropout probability, contributing
                factors and recommended interventions.
              </p>
            </div>
          </div>
        ) : (
          <div className="space-y-5">
            <div className="flex flex-col items-center gap-3 rounded-xl bg-muted/40 p-5">
              <RiskGauge score={result.probability} level={result.level} label="Dropout probability" />
              <p className={cn("font-display text-sm font-bold uppercase tracking-wider", riskStyles[result.level].text)}>
                {result.level} Risk · {result.confidence}% confidence
              </p>
            </div>
            <AIInsight title="Model explanation">{result.explanation}</AIInsight>
            <div>
              <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                Contributing factors
              </p>
              <FactorBarChart data={result.factors} dataKey="weight" labelKey="factor" height={200} />
            </div>
            <div>
              <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                Recommended interventions
              </p>
              <ul className="space-y-2">
                {result.interventions.map((it, i) => (
                  <li key={it} className="flex gap-2.5 rounded-lg border border-border px-3 py-2 text-sm">
                    <span className="grid size-5 shrink-0 place-items-center rounded-full bg-primary/12 text-[10px] font-bold text-primary">
                      {i + 1}
                    </span>
                    <span className="text-muted-foreground">{it}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}
      </SectionCard>
    </div>
  );
}
