/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PractitionerRouteImport } from './routes/practitioner'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminPractitionersRouteImport } from './routes/admin/practitioners'
import { Route as AdminPredictionsRouteImport } from './routes/admin/predictions'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as PractitionerIndexRouteImport } from './routes/practitioner/index'
import { Route as PractitionerAtRiskRouteImport } from './routes/practitioner/at-risk'
import { Route as PractitionerDashboardRouteImport } from './routes/practitioner/dashboard'
import { Route as PractitionerMessagesRouteImport } from './routes/practitioner/messages'
import { Route as PractitionerPerformanceRouteImport } from './routes/practitioner/performance'
import { Route as PractitionerPredictionsRouteImport } from './routes/practitioner/predictions'
import { Route as PractitionerProfileRouteImport } from './routes/practitioner/profile'
import { Route as PractitionerReportsRouteImport } from './routes/practitioner/reports'
import { Route as PractitionerStudentsRouteImport } from './routes/practitioner/students'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as StudentAttendanceRouteImport } from './routes/student/attendance'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as StudentMessagesRouteImport } from './routes/student/messages'
import { Route as StudentPerformanceRouteImport } from './routes/student/performance'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentProgressRouteImport } from './routes/student/progress'
import { Route as StudentRecommendationsRouteImport } from './routes/student/recommendations'
import { Route as StudentRiskRouteImport } from './routes/student/risk'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students/index'
import { Route as AdminStudentsStudentldRouteImport } from './routes/admin/students/$studentld'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionerRoute = PractitionerRouteImport.update({
  id: '/practitioner',
  path: '/practitioner',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPractitionersRoute = AdminPractitionersRouteImport.update({
  id: '/practitioners',
  path: '/practitioners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPredictionsRoute = AdminPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const PractitionerIndexRoute = PractitionerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PractitionerRoute,
} as any)
const PractitionerAtRiskRoute = PractitionerAtRiskRouteImport.update({
  id: '/at-risk',
  path: '/at-risk',
  getParentRoute: () => PractitionerRoute,
} as any)
const PractitionerDashboardRoute = PractitionerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PractitionerRoute,
} as any)
const PractitionerMessagesRoute = PractitionerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PractitionerRoute,
} as any)
const PractitionerPerformanceRoute = PractitionerPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => PractitionerRoute,
} as any)
const PractitionerPredictionsRoute = PractitionerPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => PractitionerRoute,
} as any)
const PractitionerProfileRoute = PractitionerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PractitionerRoute,
} as any)
const PractitionerReportsRoute = PractitionerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PractitionerRoute,
} as any)
const PractitionerStudentsRoute = PractitionerStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => PractitionerRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPerformanceRoute = StudentPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRecommendationsRoute = StudentRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRiskRoute = StudentRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => StudentRoute,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsStudentldRoute = AdminStudentsStudentldRouteImport.update({
  id: '/students/$studentld',
  path: '/students/$studentld',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/practitioner': typeof PractitionerRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/practitioners': typeof AdminPractitionersRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/practitioner/at-risk': typeof PractitionerAtRiskRoute
  '/practitioner/dashboard': typeof PractitionerDashboardRoute
  '/practitioner/messages': typeof PractitionerMessagesRoute
  '/practitioner/performance': typeof PractitionerPerformanceRoute
  '/practitioner/predictions': typeof PractitionerPredictionsRoute
  '/practitioner/profile': typeof PractitionerProfileRoute
  '/practitioner/reports': typeof PractitionerReportsRoute
  '/practitioner/students': typeof PractitionerStudentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/performance': typeof StudentPerformanceRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/recommendations': typeof StudentRecommendationsRoute
  '/student/risk': typeof StudentRiskRoute
  '/admin/': typeof AdminIndexRoute
  '/practitioner/': typeof PractitionerIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/students/$studentld': typeof AdminStudentsStudentldRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/practitioners': typeof AdminPractitionersRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/practitioner/at-risk': typeof PractitionerAtRiskRoute
  '/practitioner/dashboard': typeof PractitionerDashboardRoute
  '/practitioner/messages': typeof PractitionerMessagesRoute
  '/practitioner/performance': typeof PractitionerPerformanceRoute
  '/practitioner/predictions': typeof PractitionerPredictionsRoute
  '/practitioner/profile': typeof PractitionerProfileRoute
  '/practitioner/reports': typeof PractitionerReportsRoute
  '/practitioner/students': typeof PractitionerStudentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/performance': typeof StudentPerformanceRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/recommendations': typeof StudentRecommendationsRoute
  '/student/risk': typeof StudentRiskRoute
  '/admin': typeof AdminIndexRoute
  '/practitioner': typeof PractitionerIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/students/$studentld': typeof AdminStudentsStudentldRoute
  '/admin/students': typeof AdminStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/practitioner': typeof PractitionerRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/practitioners': typeof AdminPractitionersRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/practitioner/at-risk': typeof PractitionerAtRiskRoute
  '/practitioner/dashboard': typeof PractitionerDashboardRoute
  '/practitioner/messages': typeof PractitionerMessagesRoute
  '/practitioner/performance': typeof PractitionerPerformanceRoute
  '/practitioner/predictions': typeof PractitionerPredictionsRoute
  '/practitioner/profile': typeof PractitionerProfileRoute
  '/practitioner/reports': typeof PractitionerReportsRoute
  '/practitioner/students': typeof PractitionerStudentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/performance': typeof StudentPerformanceRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/recommendations': typeof StudentRecommendationsRoute
  '/student/risk': typeof StudentRiskRoute
  '/admin/': typeof AdminIndexRoute
  '/practitioner/': typeof PractitionerIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/students/$studentld': typeof AdminStudentsStudentldRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/practitioner'
    | '/student'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/messages'
    | '/admin/practitioners'
    | '/admin/predictions'
    | '/admin/reports'
    | '/admin/settings'
    | '/practitioner/at-risk'
    | '/practitioner/dashboard'
    | '/practitioner/messages'
    | '/practitioner/performance'
    | '/practitioner/predictions'
    | '/practitioner/profile'
    | '/practitioner/reports'
    | '/practitioner/students'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/messages'
    | '/student/performance'
    | '/student/profile'
    | '/student/progress'
    | '/student/recommendations'
    | '/student/risk'
    | '/admin/'
    | '/practitioner/'
    | '/student/'
    | '/admin/students/$studentld'
    | '/admin/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/messages'
    | '/admin/practitioners'
    | '/admin/predictions'
    | '/admin/reports'
    | '/admin/settings'
    | '/practitioner/at-risk'
    | '/practitioner/dashboard'
    | '/practitioner/messages'
    | '/practitioner/performance'
    | '/practitioner/predictions'
    | '/practitioner/profile'
    | '/practitioner/reports'
    | '/practitioner/students'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/messages'
    | '/student/performance'
    | '/student/profile'
    | '/student/progress'
    | '/student/recommendations'
    | '/student/risk'
    | '/admin'
    | '/practitioner'
    | '/student'
    | '/admin/students/$studentld'
    | '/admin/students'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/practitioner'
    | '/student'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/messages'
    | '/admin/practitioners'
    | '/admin/predictions'
    | '/admin/reports'
    | '/admin/settings'
    | '/practitioner/at-risk'
    | '/practitioner/dashboard'
    | '/practitioner/messages'
    | '/practitioner/performance'
    | '/practitioner/predictions'
    | '/practitioner/profile'
    | '/practitioner/reports'
    | '/practitioner/students'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/messages'
    | '/student/performance'
    | '/student/profile'
    | '/student/progress'
    | '/student/recommendations'
    | '/student/risk'
    | '/admin/'
    | '/practitioner/'
    | '/student/'
    | '/admin/students/$studentld'
    | '/admin/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PractitionerRoute: typeof PractitionerRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioner': {
      id: '/practitioner'
      path: '/practitioner'
      fullPath: '/practitioner'
      preLoaderRoute: typeof PractitionerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/practitioners': {
      id: '/admin/practitioners'
      path: '/practitioners'
      fullPath: '/admin/practitioners'
      preLoaderRoute: typeof AdminPractitionersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/predictions': {
      id: '/admin/predictions'
      path: '/predictions'
      fullPath: '/admin/predictions'
      preLoaderRoute: typeof AdminPredictionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/practitioner/': {
      id: '/practitioner/'
      path: '/'
      fullPath: '/practitioner/'
      preLoaderRoute: typeof PractitionerIndexRouteImport
      parentRoute: typeof PractitionerRoute
    }
    '/practitioner/at-risk': {
      id: '/practitioner/at-risk'
      path: '/at-risk'
      fullPath: '/practitioner/at-risk'
      preLoaderRoute: typeof PractitionerAtRiskRouteImport
      parentRoute: typeof PractitionerRoute
    }
    '/practitioner/dashboard': {
      id: '/practitioner/dashboard'
      path: '/dashboard'
      fullPath: '/practitioner/dashboard'
      preLoaderRoute: typeof PractitionerDashboardRouteImport
      parentRoute: typeof PractitionerRoute
    }
    '/practitioner/messages': {
      id: '/practitioner/messages'
      path: '/messages'
      fullPath: '/practitioner/messages'
      preLoaderRoute: typeof PractitionerMessagesRouteImport
      parentRoute: typeof PractitionerRoute
    }
    '/practitioner/performance': {
      id: '/practitioner/performance'
      path: '/performance'
      fullPath: '/practitioner/performance'
      preLoaderRoute: typeof PractitionerPerformanceRouteImport
      parentRoute: typeof PractitionerRoute
    }
    '/practitioner/predictions': {
      id: '/practitioner/predictions'
      path: '/predictions'
      fullPath: '/practitioner/predictions'
      preLoaderRoute: typeof PractitionerPredictionsRouteImport
      parentRoute: typeof PractitionerRoute
    }
    '/practitioner/profile': {
      id: '/practitioner/profile'
      path: '/profile'
      fullPath: '/practitioner/profile'
      preLoaderRoute: typeof PractitionerProfileRouteImport
      parentRoute: typeof PractitionerRoute
    }
    '/practitioner/reports': {
      id: '/practitioner/reports'
      path: '/reports'
      fullPath: '/practitioner/reports'
      preLoaderRoute: typeof PractitionerReportsRouteImport
      parentRoute: typeof PractitionerRoute
    }
    '/practitioner/students': {
      id: '/practitioner/students'
      path: '/students'
      fullPath: '/practitioner/students'
      preLoaderRoute: typeof PractitionerStudentsRouteImport
      parentRoute: typeof PractitionerRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/performance': {
      id: '/student/performance'
      path: '/performance'
      fullPath: '/student/performance'
      preLoaderRoute: typeof StudentPerformanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/recommendations': {
      id: '/student/recommendations'
      path: '/recommendations'
      fullPath: '/student/recommendations'
      preLoaderRoute: typeof StudentRecommendationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/risk': {
      id: '/student/risk'
      path: '/risk'
      fullPath: '/student/risk'
      preLoaderRoute: typeof StudentRiskRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$studentld': {
      id: '/admin/students/$studentld'
      path: '/students/$studentld'
      fullPath: '/admin/students/$studentld'
      preLoaderRoute: typeof AdminStudentsStudentldRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPractitionersRoute: typeof AdminPractitionersRoute
  AdminPredictionsRoute: typeof AdminPredictionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStudentsStudentldRoute: typeof AdminStudentsStudentldRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPractitionersRoute: AdminPractitionersRoute,
  AdminPredictionsRoute: AdminPredictionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminStudentsStudentldRoute: AdminStudentsStudentldRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PractitionerRouteChildren {
  PractitionerAtRiskRoute: typeof PractitionerAtRiskRoute
  PractitionerDashboardRoute: typeof PractitionerDashboardRoute
  PractitionerMessagesRoute: typeof PractitionerMessagesRoute
  PractitionerPerformanceRoute: typeof PractitionerPerformanceRoute
  PractitionerPredictionsRoute: typeof PractitionerPredictionsRoute
  PractitionerProfileRoute: typeof PractitionerProfileRoute
  PractitionerReportsRoute: typeof PractitionerReportsRoute
  PractitionerStudentsRoute: typeof PractitionerStudentsRoute
  PractitionerIndexRoute: typeof PractitionerIndexRoute
}

const PractitionerRouteChildren: PractitionerRouteChildren = {
  PractitionerAtRiskRoute: PractitionerAtRiskRoute,
  PractitionerDashboardRoute: PractitionerDashboardRoute,
  PractitionerMessagesRoute: PractitionerMessagesRoute,
  PractitionerPerformanceRoute: PractitionerPerformanceRoute,
  PractitionerPredictionsRoute: PractitionerPredictionsRoute,
  PractitionerProfileRoute: PractitionerProfileRoute,
  PractitionerReportsRoute: PractitionerReportsRoute,
  PractitionerStudentsRoute: PractitionerStudentsRoute,
  PractitionerIndexRoute: PractitionerIndexRoute,
}

const PractitionerRouteWithChildren = PractitionerRoute._addFileChildren(
  PractitionerRouteChildren,
)

interface StudentRouteChildren {
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentPerformanceRoute: typeof StudentPerformanceRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentRecommendationsRoute: typeof StudentRecommendationsRoute
  StudentRiskRoute: typeof StudentRiskRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentPerformanceRoute: StudentPerformanceRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentRecommendationsRoute: StudentRecommendationsRoute,
  StudentRiskRoute: StudentRiskRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PractitionerRoute: PractitionerRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
